instance_type = "t3.medium"
region = "eu-central-1"
ami_owner = "099720109477"
source_ami_name = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
vpc_name = "Talent-Academy"
subnet_name = "public_az_a"